name: 'Docker action'
descrption: 'Run the hello world thing'
inputs:
  who-to-greet:
    required: true
    default: 'world'
outputs:
  time:
    description: 'Current time'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
